[package]
name = "aoc-2024-d7"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
nom = "7.1.3"
rayon = "1.10.0"

[dev-dependencies]
divan = "0.1.17"

[[bench]]
name = "aoc-2024-d7-bench"
path = "benches/benchmarks.rs"
harness = false
